### ISSUE TITLE
Error java.lang.IllegalArgumentException: No Retrofit annotation found. (parameter #2)

### ISSUE THREAD

**Issue by tHEO2k17** [probelalkhan/android-mvvm-architecture#1]
I am getting this error.. any help

**Comment by probelalkhan** [comment]
You should explain everything. Where you are getting error? What you Did? Some screenshot and every detail. 
Right now your issue makes no sense at all.

**Comment by tHEO2k17** [comment]
thanks.. i got it solved. i realised i was using an older version of retrofit and it didn't support Response as a return type.
